index:
    path: /
    controller: App\Controller\AccueilController::indexAction

#Gérer habitation

indexHabitation:
    path: /habitation
    controller: App\Controller\HabitationController::index

listerHabitation:
    path: /habitation/lister
    controller : App\Controller\HabitationController::listerHabitation

ajouterHabitation:
    path: /habitation/ajouter
    controller : App\Controller\HabitationController::ajouterHabitation

consulterHabitation:
    path: /habitation/consulter
    controller : App\Controller\HabitationController::consulterHabitation
 
#Mentions Legales

mentionsLegales:
    path: /mentionsLegales
    controller: App\Controller\MentionLegalesController::pageMentionsLegales
