#index:
#    path: /
#    controller: App\Controller\DefaultController::index
#Mentions Legales
mentionsLegales:
    path: /mentionsLegales
    controller: App\Controller\MentionLegalesController::pageMentionsLegales
#
#