#Accueil
index:
    path: /
    controller: App\Controller\AccueilController::indexAction
    
#Authentification 
connexion:
    path: /connexion
    controller: App\Controller\AuthentificationController::connexionAction
    
deconnexion:
    path: /deconnexion
    controller: App\Controller\AuthentificationController::deconnexionAction

#Habitations
listerHabitation:
    path: /habitation
    controller : App\Controller\HabitationController::listerHabitation

ajouterHabitation:
    path: /habitation/ajouter
    controller : App\Controller\HabitationController::ajouterHabitation

consulterHabitation:
    path: /habitation/{id}
    controller : App\Controller\HabitationController::consulterHabitation
    requirements:
        id: '\d+'
        
modifierHabitation:
    path: /habitation/{id}/modifier
    controller : App\Controller\HabitationController::modifierHabitation
    requirements:
        id: '\d+'
        
archiverHabitation:
    path: /habitation/{id}/archiver
    controller : App\Controller\HabitationController::archiverHabitation
    requirements:
        id: '\d+'
containersHabitation:
    path: /habitation/{id}/container
    controller : App\Controller\ContainerController::containersHabitation
    requirements:
        id: '\d+'
#Levees
leveesMois:
    path : /levee
    controller : App\Controller\LeveesDetailController::detailMoisEnCoursAction 
  
leveesDetail:
    path : /levee/{month}/{year}
    controller : App\Controller\LeveesDetailController::detailMois 
    requirements:
        month: '\d+'
        year: '\d+'
    
leveesAnnee:
    path : /levee/anciennes
    controller : App\Controller\LeveesDetailController::detailAnneeEnCoursAction 
    
leveesPDF:
    path : /levee/{month}/{year}/pdf
    controller : App\Controller\LeveesDetailController::pdfDetailMois

#Mentions Legales
mentionsLegales:
    path: /mentionsLegales
    controller: App\Controller\MentionLegalesController::pageMentionsLegales
    
#Reclamations
listerReclamations:
    path: /reclamation
    controller: App\Controller\ReclamationController::listerReclamations
    
ajouterReclamation:
    path: /reclamation/ajouter
    controller: App\Controller\ReclamationController::ajouterReclamation
    
consulterReclamation:
    path : /reclamation/{id}
    controller : App\Controller\ReclamationController::consulterReclamation
    requirements:
        id: '\d+'
    
# Compte

listerCompte:
    path: /compte
    controller: App\Controller\CompteController::listerCompte
    
consulterCompte:
    path: /compte/{id}
    controller: App\Controller\CompteController::consulterCompte
    requirements:
        id: '\d+'
        
ajouterCompte:
    path: /compte/ajouter
    controller: App\Controller\CompteController::ajouterCompte
    
modifierCompte:
    path: /compte/{id}/modifier
    controller: App\Controller\CompteController::modifierCompte
    requirements:
        id: '\d+'

archiverCompte:
    path: /compte/{id}/archiver
    controller: App\Controller\CompteController::archiverCompte
    requirements:
        id: '\d+'

reinitMdpCompte:
    path: /compte/{id}/reinitMdp
    controller: App\Controller\CompteController::reinitMdpCompte
    requirements:
        id: '\d+'

#TypeDechet
listerTypeDechet:
    path: /typeDechet
    controller : App\Controller\TypeDechetController::listerTypeDechet

ajouterTypeDechet:
    path: /typeDechet/ajouter
    controller : App\Controller\TypeDechetController::ajouterTypeDechet
        
modifierTypeDechet:
    path: /typeDechet/{id}/modifier
    controller : App\Controller\TypeDechetController::modifierTypeDechet
    requirements:
        id: '\d+'
        
archiverTypeDechet:
    path: /typeDechet/{id}/archiver
    controller : App\Controller\TypeDechetController::archiverTypeDechet
    requirements:
        id: '\d+'


# Usager
listerUsager:
    path: /usager
    controller: App\Controller\UsagerController::listerUsager

consulterUsager:
    path: /usager/{id}
    controller: App\Controller\UsagerController::consulterUsager
    requirements:
        id: '\d+'

ajouterUsager:
    path: /usager/ajouter
    controller: App\Controller\UsagerController::ajouterUsager

modifierUsager:
    path: /usager/{id}/modifier
    controller: App\Controller\UsagerController::modifierUsager
    requirements:
        id: '\d+'

archiverUsager:
    path: /usager/{id}/archiver
    controller: App\Controller\UsagerController::archiverUsager
    requirements:
        id: '\d+'

habitationsUsager:
    path: /usager/{id}/habitations
    controller: App\Controller\HabitationController::habitationsUsager
    requirements:
        id: '\d+'

#Responsable
consulterResponsable:
    path: /responsable/{id}
    controller: App\Controller\ResponsableController::consulterResponsable
    requirements:
        id: '\d+'

listerResponsable:
    path: /responsable
    controller: App\Controller\ResponsableController::listerResponsable
    
ajouterResponsable:
    path: /responsable/ajouter
    controller: App\Controller\ResponsableController::ajouterResponsable

modifierResponsable:
    path: /responsable/{id}/modifier
    controller: App\Controller\ResponsableController::modifierResponsable
    requirements:
        id: '\d+'

archiverResponsable:
    path: /responsable/{id}/archiver
    controller: App\Controller\ResponsableController::archiverResponsable
    requirements:
        id: '\d+'

# Container (conteneurs en français)
listerContainer:
    path: /container
    controller: App\Controller\ContainerController::listerContainer

consulterContainer:
    path: /container/{id}
    controller: App\Controller\ContainerController::consulterContainer
    requirements:
        id: '\d+'

ajouterContainer:
    path: /container/ajouter
    controller: App\Controller\ContainerController::ajouterContainer

modifierContainer:
    path: /container/{id}/modifier
    controller: App\Controller\ContainerController::modifierContainer
    requirements:
        id: '\d+'

archiverContainer:
    path: /container/{id}/archiver
    controller: App\Controller\ContainerController::archiverContainer
    requirements:
        id: '\d+'


   

