index:
    path: /
    controller: App\Controller\AccueilController::indexAction

#Gérer habitation

listerHabitation:
    path: /habitation/lister
    controller : App\Controller\HabitationController::listerHabitation
 
#Mentions Legales

mentionsLegales:
    path: /mentionsLegales
    controller: App\Controller\MentionLegalesController::pageMentionsLegales
