
#Gérer habitation

indexHabitation:
    path: /habitation
    controller: App\Controller\HabitationController::index

listerHabitation:
    path: /habitation/lister
    controller : App\Controller\HabitationController::listerHabitation
 
#Mentions Legales

mentionsLegales:
    path: /mentionsLegales
    controller: App\Controller\MentionLegalesController::pageMentionsLegales

