#Accueil
index:
    path: /
    controller: App\Controller\AccueilController::indexAction
    
#Authentification 
connexion:
    path: /connexion
    controller: App\Controller\AuthentificationController::connexionAction
    
deconnexion:
    path: /deconnexion
    controller: App\Controller\AuthentificationController::deconnexionAction

#Habitation

listerHabitation:
    path: /habitation
    controller : App\Controller\HabitationController::listerHabitation

ajouterHabitation:
    path: /habitation/ajouter
    controller : App\Controller\HabitationController::ajouterHabitation

consulterHabitation:
    path: /habitation/{id}
    controller : App\Controller\HabitationController::consulterHabitation
 
leveesDetail:
    path : levees
    controller : App\Controller\LeveesDetailController::detailMoisEnCoursAction 

#Mentions Legales

mentionsLegales:
    path: /mentionsLegales
    controller: App\Controller\MentionLegalesController::pageMentionsLegales
