#Accueil
index:
    path: /
    controller: App\Controller\AccueilController::indexAction
    
#Authentification 
connexion:
    path: /connexion
    controller: App\Controller\AuthentificationController::connexionAction
    
deconnexion:
    path: /deconnexion
    controller: App\Controller\AuthentificationController::deconnexionAction

#Habitation

listerHabitation:
    path: /habitation/lister
    controller : App\Controller\HabitationController::listerHabitation
 
#Mentions Legales

mentionsLegales:
    path: /mentionsLegales
    controller: App\Controller\MentionLegalesController::pageMentionsLegales
