#Accueil
index:
    path: /
    controller: App\Controller\AccueilController::indexAction
    
#Authentification 
connexion:
    path: /connexion
    controller: App\Controller\AuthentificationController::connexionAction
    
deconnexion:
    path: /deconnexion
    controller: App\Controller\AuthentificationController::deconnexionAction

#Habitation

listerHabitation:
    path: /habitation
    controller : App\Controller\HabitationController::listerHabitation

ajouterHabitation:
    path: /habitation/ajouter
    controller : App\Controller\HabitationController::ajouterHabitation

consulterHabitation:
    path: /habitation/consulter/{id}
    controller : App\Controller\HabitationController::consulterHabitation

modifierHabitation:
    path: /habitation/modifier/{id}
    controller : App\Controller\HabitationController::modifierHabitation

archiverHabitation:
    path: /habitation/archiver/{id}
    controller : App\Controller\HabitationController::archiverHabitation

#levees

leveesDetail:
    path : levees
    controller : App\Controller\LeveesDetailController::detailMoisEnCoursAction 

#Reclamation

listerReclamations:
    path: /reclamation
    controller: App\Controller\ReclamationController::listerReclamations
    
#Mentions Legales

mentionsLegales:
    path: /mentionsLegales
    controller: App\Controller\MentionLegalesController::pageMentionsLegales
# Compte
listerCompte:
    path: /compte
    controller: App\Controller\CompteController::listerCompte
consulterCompte:
    path: /compte/{id}
    controller: App\Controller\CompteController::consulterCompte
    requirements:
        id: '\d+'
ajouterCompte:
    path: /compte/ajouter
    controller: App\Controller\CompteController::ajouterCompte
modifierCompte:
    path: /compte/{id}/modifier
    controller: App\Controller\CompteController::modifierCompte
archiverCompte:
    path: /compte/{id}/archiver
    controller: App\Controller\CompteController::archiverCompte
reinitMdpCompte:
    path: /compte/{id}/reinitMdp
    controller: App\Controller\CompteController::reinitMdpCompte
# Usager